// Account Token
export const ACCOUNT_REFRESH_TOKEN = 'DCS_OV_ACCOUNT_REFRESH_TOKEN'
export const ACCOUNT_TOKEN = 'DCS_OV_ACCOUNT_TOKEN'

// RSA Public Key
export const RSA_PUBLIC_KEY =
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo7YjzgvOO4hq1c2pm3UxSnELnHJAMuxf3e4X32y8yIoot6/XTTqra96vwnsZN54+BRRNSXzVt0rD9xHKOgqKQbdm9nmTmnGWeAJRRe7Jow18EoQn2v+M4EHBhQAxq+A06xQhZUBKcpGEw6D2KfxreL8CuINscwUMSW2f2PdUP5CP56QUsRVDlH3x7D04GYt89Qi0Xn++5Jl6JVQCZA6f2Nl/cSoyHHFS3CFSP9QrEBNHUaRsjUsGo+y+fizK2X0Xaqgthon7UY1EiVIkYdQu1Ex7U/Cjdku8AKzQr06KfTdj+O5iZslrxPEZh3jvqVz1E3bJTQ2OSbWo2ODS4kFBDwIDAQAB'

// Language
export const LANGUAGE: 'en' | 'zh_hans' | 'zh_hant' = 'en'
